language: python
python:
        - '3.8'

install:
        - pip install -r requirements-dev.txt

env:
        - PYTHONPATH=/home/travis/build/ecabreja623/PutMeOn

script:
        - make tests

deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: put-me-on
          on:
                  branch: master
