language: python
python:
        - '3.8'

install:
        - pip install -r requirements-dev.txt

env:
        - PYTHONPATH=/home/travis/build/ecabreja623/PutMeOn

script:
        - make all_tests

before_deploy:
        - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: put-me-on
          on:
                  branch: master
